package org.maxicp.cp.engine.nogoods;

import java.util.ArrayDeque;
import java.util.ArrayList;

import org.maxicp.cp.engine.core.CPConstraint;
import org.maxicp.cp.engine.core.CPSolver;
import org.maxicp.search.DFSListener;
import org.maxicp.search.DFSearch;

public class NoGoodGenerator {
    private class NGListener implements DFSListener {
        protected boolean currentlyExecutingBranchingAction = false;
        protected ArrayList<CPConstraint> currentBranchingConstraints = null;

        @Override
        public void fail(int id, int pId) {
            assert currentlyExecutingBranchingAction;
            currentlyExecutingBranchingAction = false;
            nodeDone(id, pId, currentBranchingConstraints, false);
        }

        @Override
        public void branch(int id, int pId) {
            assert currentlyExecutingBranchingAction;
            currentlyExecutingBranchingAction = false;
            nodeDone(id, pId, currentBranchingConstraints, true);
        }

        @Override
        public void branchingAction(Runnable action) {
            currentlyExecutingBranchingAction = true;
            currentBranchingConstraints = new ArrayList<>();
        }

        @Override
        public void solution(int id, int pId) {
            assert !currentlyExecutingBranchingAction;
            nodeIsSolution(id, pId);
        }

        public void beforeConstraintPosted(CPConstraint c) {
            if (!currentlyExecutingBranchingAction)
                return; // no need to store anything
            if (solver.isFixPointRunning())
                return; // this is a constraint added as a consequence of the fix-point, we only want to
                        // store constraints that are added as a consequence of branching decisions
            currentBranchingConstraints.add(c);
        }
    }

    /**
     * Stores the constraints added at each node of the search tree.
     * Seen during construction, branchingConstraints has the property that
     * 1) it is non-empty
     * 2) at the entries except the last one have been refuted (that is, the search
     * has backtracked from them)
     * 3) the last entry is ongoing (that is, the search is currently exploring the
     * subtree below this node)
     */
    public record NodeStatus(int nodeId, ArrayList<ArrayList<CPConstraint>> branchingConstraints, boolean isSolution) {
    }

    protected CPSolver solver;
    protected DFSearch search;
    protected NGListener ngListener;
    protected ArrayDeque<NodeStatus> nodeStatuses = new ArrayDeque<>();

    public NoGoodGenerator(CPSolver solver, DFSearch search) {
        this.solver = solver;
        this.search = search;
        ngListener = new NGListener();
        solver.onBeforeConstraintPosted(ngListener::beforeConstraintPosted);
        search.setDFSListener(ngListener);
    }

    public void clear() {
        nodeStatuses.clear();
        ngListener.currentlyExecutingBranchingAction = false;
        ngListener.currentBranchingConstraints = null;
    }

    protected void nodeDone(int id, int pId, ArrayList<CPConstraint> branchingConstraints, boolean ongoing) {
        while (nodeStatuses.size() != 0 && nodeStatuses.getLast().nodeId != pId)
            nodeStatuses.removeLast();

        // Add a new node if needed (if the stack is empty)
        if (nodeStatuses.size() == 0)
            nodeStatuses.addLast(new NodeStatus(pId, new ArrayList<>(), false));

        nodeStatuses.getLast().branchingConstraints.add(branchingConstraints);
        if (ongoing)
            nodeStatuses.addLast(new NodeStatus(id, new ArrayList<>(), false));
    }

    protected void nodeIsSolution(int id, int pId) {
        while (nodeStatuses.size() != 0 && nodeStatuses.getLast().nodeId != pId)
            nodeStatuses.removeLast();
        assert nodeStatuses.size() != 0;
        NodeStatus last = nodeStatuses.removeLast();
        nodeStatuses.addLast(new NodeStatus(last.nodeId, last.branchingConstraints, true));
    }

    /**
     * Returns the no-good constraints generated by the search so far, in the form
     * of an array of array of constraints, where each entry of the first array
     * corresponds to a node of the search tree and contains the list of constraints
     * that have been added as branching decisions in the subtree below this node.
     * Note that all the nodes except maybe the last one are refuted (that is, the
     * search has backtracked from them) while the last one is ongoing (that is, the
     * search is currently exploring the subtree below this node).
     * 
     * If the last node is a solution, a fake decision (null) is added to
     * the no-good to represent that the previous one is done.
     */
    public CPConstraint[][][] getNoGood() {
        int nbEmptyNodes = 0;
        for (NodeStatus status : nodeStatuses) {
            if (status.branchingConstraints.size() == 0)
                nbEmptyNodes++;
        }

        if (nodeStatuses.size() == 0)
            throw new IllegalStateException("No node status available, cannot extract no-good");

        boolean lastIsSolution = nodeStatuses.getLast().isSolution();

        assert nbEmptyNodes <= 1; // at most one node can be empty, the last one (the ongoing one) may not have
                                  // generated any constraint yet

        CPConstraint[][][] result = new CPConstraint[nodeStatuses.size() - nbEmptyNodes][][];
        int i = 0;
        for (NodeStatus status : nodeStatuses) {
            ArrayList<ArrayList<CPConstraint>> branchingConstraints = status.branchingConstraints;
            if (branchingConstraints.size() == 0)
                continue;
            int size = branchingConstraints.size();

            boolean isLast = (i == nodeStatuses.size() - nbEmptyNodes - 1);
            if (isLast && lastIsSolution)
                size++; // if the last node is a solution, we want to include it in the no-good as well
            result[i] = new CPConstraint[size][];
            for (int j = 0; j < branchingConstraints.size(); j++) {
                ArrayList<CPConstraint> nodeConstraints = branchingConstraints.get(j);
                result[i][j] = nodeConstraints.toArray(new CPConstraint[nodeConstraints.size()]);
            }
            if (isLast && lastIsSolution)
                result[i][size - 1] = null; // if the last node is a solution, we include it as an empty
                                            // set of constraints
            i++;
        }
        return result;
    }
}
